### ISSUE TITLE
"ansicolor brightness hierarchy works" test failing

### ISSUE THREAD

**Issue by brettz9** [xpl/ansicolor#1]
Nice project!

Before discovering your work, I had already adapted [this branch](https://github.com/brettz9/chalk256/tree/universal-api) of my chalk fork to support returning results as arrays, to allow spreading within console calls in a cross-platform friendly manner (as well as utility methods to avoid the need for spreading).

I came across your project finding your browser side parsing useful but then realized my API enhancements don't mean as much without the hierarchy problem that you outlined fixed (since I'm not using your code for that).

But before getting into your code, since I see your "ansicolor brightness hierarchy works" test is currently failing (despite your other hierarchical test working), I was wondering whether this were just a trivial regression or something that needed more serious revisions.

(FWIW, I'd also like to see color ranges, other non-colors, or even non-styles (like clear screen) be potentially supported, as a fork at least if extensibility isn't something you'd like to see. And I see what could potentially be the workings of HTML export within your code which sounds cool to me too...)

**Comment by xpl** [comment]
Thanks for your great feedback!

I've fixed that issue with brightness hierarchy. The reason it was failing is just because I haven't yet implemented it, as it's somewhat non-trivial... But now it seems to be solved.

P.S. Your contributions are welcomed! If you want to add more features, this would be great.
