### ISSUE TITLE
Another apparent hierarchy issue

### ISSUE THREAD

**Issue by brettz9** [xpl/ansicolor#3]
Hi,

Just looking at submitting a PR for HTML export, but still seeing some apparent hierarchy problem which I was wondering if you could take a look at:

```js
'foo' + ('bar'.red.underline.bright + 'baz').green.underline + 'qux'
```

...is showing up with "qux" in (dark) red whereas I would expect the default white.

**Comment by brettz9** [comment]
...or for a further simplified test case that also fails:

```js
('bar'.red + 'baz').green.underline + 'qux'
```

**Comment by xpl** [comment]
Thank you for pointing that problem out. It led me to re-thinking the underlying algorithm, greatly simplifying it (down to a single line of code), and it seems to be working well now. At least, I hope so... :)
