### ISSUE TITLE
Overcoming API limitations (independent color instance objects, safer prototypes, and polyglot logging)

### ISSUE THREAD

**Issue by brettz9** [xpl/ansicolor#4]
In addition to stylistic forms like this:

```js
'foo' + ('bar'.red.underline.bright.inverse + 'baz').bgGreen
```

I wanted to add themes something like this:

```js
color.setTheme({
    serious: ['red', 'underline', 'bright', 'inverse'], // As arrays
    ok: 'bgGreen', // As strings
    warning: ['background:rgba(255,255,0,1)'], // With arbitrary CSS for browser only
    strong: 'color:rgba(255, 50, 0, 0)', // With arbitrary CSS for browser only
});
```

And then build strings like this:
```js
'foo' + ('bar'.serious + 'baz').ok
```

However (and beyond the usual prototype-overriding concerns), `ansicolor`'s approach in merely building strings prevents us from reliably changing themes within an application if the prototype approach is used.  So a subsequent call to `setTheme` would overwrite the Prototype, making code still relying on the first theme used no longer work.

While I can solve this by building a wrapper library around ansicolor, I wanted to see if you were open to considering a different approach to your API that would avoid this problem and, in the process, also avoid the more critical challenge that your API currently has no built-in way to allow the user to express logging in a manner that work in both the browser and Node.

The trade-off would be that one could no longer directly supply the colored strings to `console.log` in the same manner (if using themes).

Such an API could work by letting the user build strings which were not legitimate ANSI or browser console arguments (though they could be quite similar, requiring minimal changes to your code) but which could be parsed into legitimate ANSI or browser arguments (including more expressive ones which only worked in the browser or HTML export).

```js
var Color = require('ansicolor');

var test = Color({config}); // Allow defining separate instances without calling `parse`
test.setTheme(...); // This would now be instance-sensitive

// The default would auto-detect and not require this
// test.setMode = 'node';
// test.setMode = 'browser'; // as in `console.log('%cHello', 'color:red')`
// test.setMode = 'html'; // append HTML export to document.body or an element targeted by
                      // `document.querySelector()` if set, e.g., by `color.htmlTarget = '.log';`
test.log('foo' + ('bar'.serious + 'baz').ok); // The string prototype methods would bake in
                     // the theme names rather than the colors so as to allow applying the
                     // current theme only on this `color` instance (`test`).

// Use another theme
var app = Color({theme: {...}});
app.log(...);

// Although console.log would not work, at least when used with themes
//   or in the browser, a method could be provided (or the instance object
//   could itself be a constructor) to return an array
//   which could be spread to work in Node or the browser (though I think
//   the convenience method ought to be generally preferred).
console.log(...test('foo' + ('bar'.serious + 'baz').ok));
```

**Comment by xpl** [comment]
Hi! What you propose is perfectly meaningful – it would be really nice to have themes and logging stuff. But the point of this library is to be a lightweight middleware for more complex and specific APIs.

For instance, the actual cross-platform logging API (an abstraction over `console.log`) is supposed to be implemented in a separate higher-level library which would utilize Ansicolor as a helper to convert ANSI codes to whatever, depending on a platform.

This is sometimes called a "small modules" approach, where you try to keep things as simple and minimalistic as possible, to enable broader use.

Ansicolor was originally separated from a [larger framework](https://github.com/xpl/useless) (which was awfully written, but I learned a lot from this), along with several other nano-libraries, each serving a specific purpose:

* [String.ify](https://github.com/xpl/string.ify) for configurable object printing
* [StackTracey](https://github.com/xpl/stacktracey) for parsing exceptions in platform-agnostic way

All these will eventually assemble into a larger library that will provide a front-end API for cross-platform logging. So basically this is the reason why I would like to stick Ansicolor to parsing/printing ANSI colors, keeping complex things away from it.

About themes, it would be nice to have ability to override the hard-coded ANSI→CSS translation. The current implementation lacks this feature.
