### ISSUE TITLE
Seems not support parsing combined ANSI code

### ISSUE THREAD

**Issue by zerbobo** [xpl/ansicolor#6]
When parsing
```
\033[0;31m
```
I get
```
\033[0;31m
```
as a text, while it's a combination of `\033[31m` and `\033[0m`, meaning RED and NoBold

**Comment by xpl** [comment]
@zerbobo Good catch. An update is coming. And by the way, `\033[0m` means `reset` (remove all styles), so it would remove the red color too, not just the bold.

**Comment by xpl** [comment]
@zerbobo Fixed in version `1.1.78`.

**Comment by zerbobo** [comment]
@xpl Perfect!
