### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by AlexLeung** [xpl/ansicolor#7]
add typescript definitions (.d.ts file) to the repo

**Comment by xpl** [comment]
I'll try to make some in the coming days.

**Comment by xpl** [comment]
@AlexLeung Yay! Typings have finally arrived:

https://github.com/xpl/ansicolor/blob/master/ansicolor.d.ts

As I don't use TS myself, any feedback would be appreciated.

**Comment by xpl** [comment]
@AlexLeung Unfortunately there is currently a problem with expressing the method chaining feature with TS types (for things like `red.bright.underline ('foo')`, but I'll figure how to express that.

**Comment by xpl** [comment]
@AlexLeung OK, I've managed to fix that problem with chaining in #493815dad84a38b9b9408929d5ed2274413d2487

Let me know if something isn't working as expected.

**Comment by AlexLeung** [comment]
Thanks for the super quick turn around time on this! I will try this out over the weekend and open an issue if I encounter anything.

**Comment by MJLHThomassen** [comment]
I have a comment on the .d.ts files. Only the ansicolor interface is exported, not all the other defined types.

Now, i can't make a class variable that has an Ansicolor type like this:

```
import * as Ansicolor from "ansicolor"; // <-- Would much prefer to see the following syntax: import { Ansicolor, ParsedSpan } from "ansicolor"; 

class Test
{
    private parsedLines: ParsedSpan[]; // <-- This is impossible atm

    public someFunc(text: String): void
    {
        this.parsedLines = Ansicolor.parse(text).spans;
    }
}
```

Would it be possible to update the .d.ts file accordingly? (basically, dont export a declared const called ansicolor of type ansicolor, but just export the interfaces directly).

**Comment by xpl** [comment]
@MJLHThomassen I'm figuring how to do what you have suggested...

> basically, dont export a declared const called ansicolor of type ansicolor, but just export the interfaces directly

The problem is that `ansicolor` is actually an object and not an interface. So how do we export both that object and other interfaces along with it?

**Comment by xpl** [comment]
@MJLHThomassen Nevermind, I'll fix it probably today. There was some f-ed up thing with that .d.ts where I tried to cut some corners and that made it not corresponding to the actual implementation — I only now realized that it might have caused troubles in people's code...

**Comment by xpl** [comment]
@MJLHThomassen Okay, now you have a whole **lot** of ways to import!

As object:

```javascript
import { ansicolor, ParsedSpan } from 'ansicolor'

ansicolor.parse (ansicolor.red.bright (something))
```

As distinct methods:

```javascript
import { red, parse, ParsedSpan } from 'ansicolor'

parse (red.bright ('foo'))
```

Old import style should work as well (not breaking the backward compatibility):

```javascript
import ansicolor from 'ansicolor'
```

Let me know if that is okay.

**Comment by MJLHThomassen** [comment]
@xpl That looks great! Thanks for the fast response. That looks exactly like i was looking for! Now i don't have to use the "any" type anymore if i need an object with a ParsedSpan field. (or define my own).
